affirmations =[
    "You are fearfully and wonderfully made in the image of God.",
    "You are loved more than you can fathom.",
    "You are chosen and wanted.",
    "Thank you for being a friend to me.",
    "I miss you!",
    "You are important and valued.",
    "You are not alone even when you feel lonely.",
    "I admire how strong you are!",
    "I love how you love on the forgotten and care for the afflicted.",
    "Your ability to make the ordinary beautiful is a true gift!",
    "I admire how you’ve taken care of yourself!",
    "You are a fighter and you never give up.",
    "You are a great wife to your husband!",
    "Thank you for being a loving mother and friend to me!",
    "You never give up even when the way before you is uncertain.",
    "I admire your tenacity and courage!",
    "You are fearfully and wonderfully made in the image of God.",
    "Your beauty and personality is unique!",
    "You have great style!",
    "I admire your never-ending selfless love for your children and grandchildren.",
    "Take heart when you are discouraged and remember our God will defend you!",
    "You are important to God’s plan no matter your relationship status.",
    "I love seeing how you listen to God.",
    "I am so proud of the woman you’ve become.",
    "Your grace and meekness are inspiring. ",
    "I love you.",
    "You are so special to me.",
    "After all of this time, I'm still so crazy for you.",
    "It really impressed me when you…",
    "Did I tell you how grateful I am that you are my partner?",
    "You deserve all of the praise at work. I see how hard you've been working.",
    "I just wanted to let you know I'm proud of you.", 
    "I really appreciate you when you do...",
    "I am here if you need me. I'm always in your corner supporting you.", 
    "I feel so loved when you...",
    "I am proud of you because...",
    "I want to take the time to thank you for how hard you work around our home.",
    "You look amazing. Is that a new outfit?",
    "I am proud of you for always trying your best, whatever it is.", 
    "It makes my heart melt watching you take care of ____.", 
    "Thank you for being so sweet and loving to my family and friends.", 
    "I'm the happiest when you make me laugh.",
    "You have the cutest crinkles when you smile.",
    "I find you so attractive and gorgeous.",
    "I'm lucky that you are my partner.",
    "I love our beautiful life together.",
    "I love how your eyes sparkle when you...",
    "Thank you for making me feel safe and loved.",
    "Thank you for listening.",
    "I missed you.",
    "I love how you get me.",
    "I’m so happy to see you.",
    "You’re the best.",
    "No one makes me [laugh as much as/feel as happy/feel as beautiful] as you do.",
    "You’re such a good partner.",
    "You help me feel like I can do anything.",
    "When I’m with you, I’m a better person.",
    "You’re the best [parent /friend/teacher/etc.].",
    "You handled that like a pro.",
    "I value your judgement.",
    "I’m so proud of you.",
    "Your support means the world to me.",
    "I love how you see the world.",
    "Thank you for being a wonderful listener.",
    "You broaden my perspective.",
    "I hope you know how much you mean to me.",
    "Being with you makes me so [happy /inspired/joyful]!",
    "I love your [smile/laugh/eyes/way of seeing things].",
    "Thank you for sharing your opinions with me.",
    "I love that I can be myself with you.",
    "Thank you for being honest with me.",
    "You’re so thoughtful.",
    "You’re so kind.",
    "You’re so sexy.",
    "My life is more meaningful with you in it.",
    "You rocked that situation.",
    "Will you help me with something? Your input/advice is always so good.",
    "I love how well you understand me.",
    "You’re the best [gift-giver /cookie-baker/dad/mom/etc.].",
    "You’re my best friend.",
    "You’re one of my favorite people to be around.",
    "You take such good care of me.",
    "You always know the right thing to say.",
    "You help me so much.",
    "Thank you for being in my life.",
    "We work so well together.",
    "You’re an inspiration!",
    "I love you.",
    "You are my sunshine.",
    "I’m sorry I hurt you.",
    "I love that you did this for me.",
    "Your being here makes everything better.",
    "It must be so tough to deal with this. How can I help?",
    "You are amazing.",
    "You inspire me.",
    "Thank you for taking the time to do this with me.",
    "You did that! Go you!",
    "I learn so much from you.",
    "I love your ideas.",
    "You do so much for the people in your life.",
    "I’m proud to be your partner.",
    "I have total confidence in you.",
    "I love how you make time for me.",
    "I respect you.",
    "I love being with you.",
    "That was so thoughtful of you to do/say.",
    "That was so kind of you to do/say.",
    "You know how to make me laugh!",
    "You know how to make me happy!",
    "I feel safe with you.",
    "You have the best sense of humor.",
    "I love when we do something special together.",
    "I’ll always be here for you.",
    "You make everything more fun.",
    "You’re such a good lover.",
    "Thanks for seeing what I need/needed.",
    "We make a great team.",
    "Hello, gorgeous.",
    "Hey there, sexy.",

]